### ISSUE TITLE
Separate service for getting WeatherLink Cloud API data

### ISSUE THREAD

**Issue by uajqq** [grebleem/WeatherLinkliveUDP#10]
I've been working on a separate weewx service to collect WeatherLink Cloud API data alongside the WeatherLinkUDP driver, so that the driver doesn't have to mess around with it:

[DavisHealthAPI](https://github.com/uajqq/weewx-davishealthapi)

This separates the WeatherLink API calls from the local API calls so we're not making an API call every 10 seconds. Additionally, by initializing a separate database to hold the information, we can record a lot more data than would be possible using the weewx database. Let me know what you think!

**Comment by grebleem** [comment]
Very nice! I will try it out later today.
