### ISSUE TITLE
Indoor temperature rises without reason

### ISSUE THREAD

**Issue by c0by85** [grebleem/WeatherLinkliveUDP#11]
Hello,

here's the problem. My internal temperature is rising for no reason. I am noticing this problem more and more often now. The console still shows 24°C, but in Weewx the temperature is rising.

`Inside Temperature 27,1°C`

![daytempin](https://user-images.githubusercontent.com/25707747/89631545-33e1ed00-d8a1-11ea-99ad-083e1f7e9044.png)
![IMG_1634_](https://user-images.githubusercontent.com/25707747/89632218-27aa5f80-d8a2-11ea-829b-96ce826bbddc.jpg)

According to the screenshot this happens almost every day.

```
weewxd --version && lsb_release -a && uname -a && wee_extension --list

4.1.1
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

Linux pi2 5.4.51-v7+ #1327 SMP Thu Jul 23 10:58:46 BST 2020 armv7l GNU/Linux

Extension Name    Version   Description
WeatherLinkLiveUDP0.2.6     Periodically poll weather data from a WeatherLink Live device
crt               0.21      Emit a Cumulus realtime.txt for LOOP data.
windy             0.7       Upload weather data to Windy.
```
Any idea?

**Comment by grebleem** [comment]
the inside temperature is reported by the wll, what is the inside temperature reporting on the WeatherLink App, or website?

**Comment by c0by85** [comment]
strange, maybe the wll got an own temp sensor? this is the reportet temp data. it would make sense. I hadn't thought of that.

![2020-08-07 16_04_17-Browse](https://user-images.githubusercontent.com/25707747/89653692-be3d4780-d8c7-11ea-8844-f2b1c3cd0c20.png)![2020-08-07 16_03_27-Browse](https://user-images.githubusercontent.com/25707747/89653694-bed5de00-d8c7-11ea-826f-5dad49d0acfe.png)

**Comment by grebleem** [comment]
Yes, the wll has its own temp and pressure sensor.
