### ISSUE TITLE
Problem with the rain from yesterday

### ISSUE THREAD

**Issue by c0by85** [grebleem/WeatherLinkliveUDP#12]
Hello,

hope it is related to the driver and not Weewx. Then this would be the wrong place for the problem.

I saw again this morning that the amount of rain is doubled at daybreak.

It had rained 7.8 mm and in Weewx there are now 15.6 mm.

How can this happen? To all weather networks 7.8 mm was reported correctly. Only in the database and in the NOAA reports it is now 15.6 mm.

![image](https://user-images.githubusercontent.com/25707747/90981944-3f513b80-e564-11ea-8480-2bfbd8d074e4.png)

Shortly before 00:00 another 7.8 mm was added.

![image](https://user-images.githubusercontent.com/25707747/90981978-80e1e680-e564-11ea-8f02-119290a2fae4.png)

Or is it related to this?

[https://github.com/grebleem/weewx-weatherlinkliveudp/issues/7](https://github.com/grebleem/weewx-weatherlinkliveudp/issues/7)

**Comment by grebleem** [comment]
Hi,

What version are you using? There is a small change the rain detection is wrong. I'm about to release the development version. All rain problems should be fixed in that version.

**Comment by c0by85** [comment]
According to wee_extensions

```
 wee_extension --list
Erweiterungsname Version Beschreibung
WeatherLinkLiveUDP0.2.6 Periodically poll weather data from a WeatherLink Live device
```

According to File content

```
DRIVER_NAME = 'WeatherLinkLiveUDP
DRIVER_VERSION = '0.2.7'
```

Downloaded as described in the manual.

`wget -O weatherlinkliveudp.zip https://github.com/grebleem/WeatherLinkLiveUDP/archive/master.zip`

**Comment by grebleem** [comment]
I uploaded version 0.2.8, please give that version a try.

**Comment by c0by85** [comment]
I have downloaded and installed it. Now we have to wait for the next rain.

Thanks for that.

**Comment by c0by85** [comment]
![image](https://user-images.githubusercontent.com/25707747/91635413-9c337280-e9f8-11ea-8736-b217f516452d.png)

Tested and passed the test. Thanks. It rained 2mm yesterday and 2mm are shown for yesterday.

Please close the issue again. I don't know if a notification will be sent out when closed.
