### ISSUE TITLE
Feature Request: Weatherlink Live usage of internal storage

### ISSUE THREAD

**Issue by ebnerjoh** [grebleem/WeatherLinkliveUDP#16]
The Weatherlink Live has an internal storage with Batterybackup to survive an power outage. 

Is it possible to take advantage of this? E.g. when weewx server is dying that the driver is collecting also the values which were created during the outage?

**Comment by grebleem** [comment]
Not at the moment. This is limited by Davis, it uses the backup to store it to the Davis WheaterLink site. It is possible to get the data from there, but that would make the driver to complicated. The best thing to do is a manual import for the lost data.
