### ISSUE TITLE
Link Quality

### ISSUE THREAD

**Issue by ebnerjoh** [grebleem/WeatherLinkliveUDP#18]
Hi, is it possible to show the link quality from ISS to WLL or is this not possible due to the API?

**Comment by grebleem** [comment]
Hi,
No not at this time, this data is stored by the wll and uploaded to Davis. It is available via WeatherLink v2 API. But to keep the driver 'simple' it is not wise to also make requests to the Davis site.

You can try this:
https://github.com/uajqq/weewx-davishealthapi
