### ISSUE TITLE
Some rain is missing today

### ISSUE THREAD

**Issue by hoevenvd** [grebleem/WeatherLinkliveUDP#20]
Weatherlink.com reports 4.4 mm today. My website reports 4.0 mm today, also 4.0mm in the database.

I've attached todays syslog

![image](https://user-images.githubusercontent.com/2419916/95455958-e4866e80-096e-11eb-8e50-c8704619819f.png)

![2020-10-08 (1)](https://user-images.githubusercontent.com/2419916/95455517-485c6780-096e-11eb-9046-7eb1bd00932b.png)
mysql> select sum(round(weewx.archive.rain,1)) from weewx.archive where from_unixtime(weewx.archive.datetime) like '2020-10-08%';
+----------------------------------+
| sum(round(weewx.archive.rain,1)) |
+----------------------------------+
|                              4.0 |
+----------------------------------+
1 row in set (14.37 sec)
[syslog.zip](https://github.com/grebleem/weewx-weatherlinkliveudp/files/5347623/syslog.zip)

**Comment by grebleem** [comment]
I was missing 0.4 yesterday. However the weewx.log showed:
`│Oct  8 19:04:14 celsius weewx[788] DEBUG user.weatherlinkliveudp: Set Previous period rain to: 89 buckets.[17.8 mm / 0.7 in]`
The same as Davis, but there was only 17.4 mm in the weewx database, so somehow the data was not picked up by weewx.
I know it produces a lot of data, but the debug options show a lot of rain data and try the October branch?

**Comment by hoevenvd** [comment]
Okay, will do. Activate debug for logging, and run the October branch. More rain to come next days, so plenty of changes to check rain correctness... Thx

**Comment by grebleem** [comment]
Fixed in v0.2.9.
