### ISSUE TITLE
rain and UDP data

### ISSUE THREAD

**Issue by roe-dl** [grebleem/WeatherLinkliveUDP#21]
I was a little bit confused about the amount of WLL drivers available, and that led me into some looking around. My problem involved rain, and changing to this drivers seems to solve it. Sometimes there are error messages regarding UDP. So I had a look into the code. And so I am still confused.

In function decode_data_wll() both http and udp data are processed. If I understand the code right, the function distinguishes between them by the following condition:
- for both of them: txid == no. of the station and data_structure_type == 1
- for UDP (variable iss_udp_data):  no value named 'temp' included
- for HTTP (variable iss_data): no further condition

The code says that UDP data (variable iss_udp_data) is used to calculate rain.

That is an json data set from my WeatherLinkLive device:
[wll-json-data.pdf](https://github.com/grebleem/weewx-weatherlinkliveudp/files/5592186/wll-json-data.pdf)

There, the section with data_structure_type==1 and temp==null does **not** include rain data at all. The data fields are there, but they never ever contain data. But that was the condition to find the UDP data in the code.

Could it be possible, that rain is not recognized because of that sometimes?

**Comment by selectSt4r** [comment]
I too am getting UDP "socket error" log entries.  Also connection refused errors with polling /v1/current_conditions.

**Comment by roe-dl** [comment]
I am wondering what I observed then in 2020. I have been using that driver since then, and there are no problems any more. So I close this issue now.
