### ISSUE TITLE
Question: would it be possible to retreive historical values from the weatherlive-link?

### ISSUE THREAD

**Issue by ebnerjoh** [grebleem/WeatherLinkliveUDP#24]
Eg. if there is an interruption of the weewx service?

Best Regards,
Johannes

**Comment by grebleem** [comment]
Currently not, the only way to retrieve historical data is with [Davis api v2 ](https://weatherlink.github.io/v2-api/). To keep this service clean and fast it is not implemented. Perhaps in the future as an separate data-service.
